# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'Refugees' do

pod 'PayPal-iOS-SDK'
#pod 'CSNotificationView', '~> 0.5'
pod 'JVFloatLabeledTextField'
pod 'UICountingLabel'
end

